services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: caddy
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data:/data
      - ./config:/config
    networks:
      - caddy

networks:
  caddy:
    name: caddy 